### ISSUE TITLE
Use Local Or Global Version And Architecture of pyenv's python by default if not specified

### ISSUE THREAD

**Issue by a2hsh** [limitedeternity/pyenv-py#1]
Hi!
I came upon this project when searching for a solution to run NVDA, an open source screen reader for windows from source using Pyenv. First, I would like to express my gratitude for such a project, as it really helped me to maximize the usage of my virtual invironment.
## Summary:
As some apps don't specify the version argument when executing python commands, assuming that the user has the python launcher installed, and to maximize compatibility with pyenv-win, it would be really benificial if pyenv-py filled out these values by default, allowing them to be changed by the user if needed.
## Expected Behavior:
When the "py" command is issued, the following checks are performed:
1. if the command line arguments for version and Architecture  are specified, use them as usual.
2. Otherwise, check if a local version is set from pyenv, and use its values for version and Architecture respectively.
3. If no local version is set, use the global version from pyenv.

Once again, thanks for this great project, and I wish you a happy holiday season.

**Comment by a2hsh** [comment]
I was reading [python-launcher](https://github.com/brettcannon/python-launcher)'s readme file, and giving this proposal some thought, especially after reading this statement:
> The goal is to have py become the cross-platform command that Python users typically use to launch an interpreter while doing development. By having a command that is version-agnostic when it comes to Python, it side-steps the "what should the python command point to?" debate by clearly specifying that upfront (i.e. the newest version of Python that can be found). This also unifies the suggested command to document for launching Python on both Windows as Unix as py has existed as the preferred [command on Windows](https://docs.python.org/3/using/windows.html#launcher) since 2012 with the release of Python 3.3.

Since we want to maximize compatibility with other python launchers, I sejest that we use another version of python if:
- a `-version` argument is specified, or
- a local pyenv python version is set.

Otherwise, we refer to the newest python version installed by pyenv.
I haven't installed python-launcher on my ubuntu WSL yet, but if someone can give any insite regarding compatibility, that would be really great.
Thank you!

**Comment by limitedeternity** [comment]
I'll look into it.
I assume the following version selection priority:
1. `-version` argument;
2. _local_ version set using pyenv;
3. _global_ version set using pyenv.
There is no reason to unconditionally default to the latest python version IMO - if you want `py` to launch it, set it as global using pyenv.

**Comment by limitedeternity** [comment]
That's too many words to ask me to respect pyenv settings =)
Will look into it. Thanks.

**Comment by a2hsh** [comment]
> That's too many words to ask me to respect pyenv settings =) Will look into it. Thanks.

Sorry, Just thought I'd be thorough 😳
Thanks!

**Comment by limitedeternity** [comment]
![Screenshot](https://user-images.githubusercontent.com/24318966/147737136-40ffa00a-5b30-4202-91dc-7d228f6a4bf2.png)

**Comment by limitedeternity** [comment]
cc @a2hsh
