### ISSUE TITLE
Where should pre-built py.exe be installed?

### ISSUE THREAD

**Issue by hwine** [limitedeternity/pyenv-py#2]
Thanks for the pre-built version!

One question, as my web searches haven't found anything  -- what's the recommended install location for local tools like this on windows? (On *nix, I'd put it in `~/.local/bin/`.) 

Or maybe the question should be: what's the common install location for rust tools on windows? I see the topic described for rust developers, but not for rust tool users.

**Comment by limitedeternity** [comment]
1. Create a directory for such tools anywhere you want
2. Put `py.exe` there
3. https://medium.com/@kevinmarkvi/how-to-add-executables-to-your-path-in-windows-5ffa4ce61a53

**Comment by limitedeternity** [comment]
![image](https://user-images.githubusercontent.com/24318966/173309342-f57f3717-05ac-49ac-b1e4-d78697f5fd19.png)
---
Actually, there is nothing like `~/.local/bin` on Windows. You can either stick to `$HOME\.cargo\bin` as mentioned above, or create any directory anywhere you want. Just don't drop untrusted binaries into `C:\Windows\System32`.

Also, don't forget to add the directory where you put `py.exe` into `$PATH`: https://medium.com/@kevinmarkvi/how-to-add-executables-to-your-path-in-windows-5ffa4ce61a53

**Comment by limitedeternity** [comment]
If no more questions left, just close the issue
