### ISSUE TITLE
Error running py.exe on Windows 11

### ISSUE THREAD

**Issue by cderv** [limitedeternity/pyenv-py#3]
After installing rustup I ran 
````
> cargo install --path .
  Installing pyenv-py v0.2.1 (C:\Users\chris\Documents\DEV_OTHER\pyenv-py)
    Updating crates.io index
  Downloaded aho-corasick v0.7.18
  Downloaded ctrlc v3.2.2
  Downloaded memchr v2.5.0
  Downloaded lazy_static v1.4.0
  Downloaded regex-syntax v0.6.27
  Downloaded regex v1.6.0
  Downloaded winapi v0.3.9
  Downloaded cfg-match v0.2.1
  Downloaded winapi-x86_64-pc-windows-gnu v0.4.0
  Downloaded 9 crates (4.9 MB) in 1.82s (largest was `winapi-x86_64-pc-windows-gnu` at 2.9 MB)
   Compiling memchr v2.5.0
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.9
   Compiling regex-syntax v0.6.27
   Compiling lazy_static v1.4.0
   Compiling cfg-match v0.2.1
   Compiling aho-corasick v0.7.18
   Compiling regex v1.6.0
   Compiling ctrlc v3.2.2
   Compiling pyenv-py v0.2.1 (C:\Users\chris\Documents\DEV_OTHER\pyenv-py)
    Finished release [optimized] target(s) in 28.34s
  Installing C:\Users\chris\scoop\persist\rustup\.cargo\bin\py.exe
   Installed package `pyenv-py v0.2.1 (C:\Users\chris\Documents\DEV_OTHER\pyenv-py)` (executable `py.exe`)
````

But I then get an error running `py.exe`

````
> py -3
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "Le chemin d’accès spécifié est introuvable." }', src/main.rs:117:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
````
but pyenv a version 3
````
> pyenv which python3
C:\Users\chris\scoop\apps\pyenv\current\pyenv-win\versions\3.9.13\python3.exe
````

Is there any other requirement to make it works ?

**Comment by limitedeternity** [comment]
Yes. There is a requirement to install pyenv **correctly**.

1. https://github.com/pyenv-win/pyenv-win#git-commands
2. https://github.com/pyenv-win/pyenv-win#add-system-settings

![](https://user-images.githubusercontent.com/24318966/180753942-335248a1-d652-4ab3-b5bb-e640e331989e.png)

**Comment by cderv** [comment]
> There is a requirement to install pyenv **correctly**.

By emphasis on the word "correctly", Do you mean to not use of the Scoop version of **pyenv-win** or you meant something else like that the environment variables are probably not the correct one ? 

Just to make this more clear for me. Thank you.

**Comment by limitedeternity** [comment]
Yeah, installation through Scoop is not officially supported. Either use Chocolatey (was using this one until their installation script broke when **pyenv-win** 3.0 got released), or `git clone` into `%USERPROFILE%\.pyenv` and setup environment variables as per documentation (that's the most reliable and recommended method btw).

**pyenv-py** resolves directory with Python installations relative to **pyenv** binary. Scoop might have wrecked the installation in some way, that's why you see `NotFound` error.

**Comment by cderv** [comment]
Ok good to know. I'll try to fix the scoop installation process in the process then. Thank you for the additional explanation !
